timezone: Europe/Stockholm

collections:
  services:
    output: false
  tickets:
    output: true

defaults:
  - scope:
      path: ""
      type: tickets
    values:
      layout: ticket
