timezone: Europe/Stockholm

collections:
  services:
    output: false
  incidents:
    output: true

defaults:
  - scope:
      path: ""
      type: incidents
    values:
      layout: incident
